//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHTD.DbObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menuer
    {
        public int id { get; set; }
        public Nullable<int> menu_id { get; set; }
        public string mingcheng { get; set; }
        public string url { get; set; }
        public Nullable<int> paixu { get; set; }
        public Nullable<short> isDel { get; set; }
    }
}
