//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHTD.DbObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int id { get; set; }
        public string sn { get; set; }
        public Nullable<int> cid { get; set; }
        public Nullable<short> tax { get; set; }
        public Nullable<int> uid { get; set; }
        public Nullable<System.DateTime> printtime { get; set; }
        public string worktime { get; set; }
        public Nullable<short> visitresult { get; set; }
        public string visitremark { get; set; }
        public Nullable<System.DateTime> visittime { get; set; }
        public Nullable<int> visituser { get; set; }
        public Nullable<short> status { get; set; }
        public Nullable<short> isDel { get; set; }
    }
}
