//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHTD.DbObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskPic
    {
        public int id { get; set; }
        public Nullable<int> tid { get; set; }
        public string path { get; set; }
        public string dist { get; set; }
        public Nullable<System.DateTime> addtime { get; set; }
    }
}
