//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHTD.DbObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskContent
    {
        public int id { get; set; }
        public Nullable<int> tid { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<System.DateTime> requesttime { get; set; }
        public string content { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<int> createuser { get; set; }
        public Nullable<short> ismain { get; set; }
        public Nullable<decimal> feiyong { get; set; }
    }
}
