//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskMgt.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Constant_Detail
    {
        public int c_id { get; set; }
        public Nullable<int> c_cId { get; set; }
        public string c_key { get; set; }
        public string c_value { get; set; }
        public Nullable<int> c_isDel { get; set; }
    }
}
