//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskMgt.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskVisit
    {
        public int id { get; set; }
        public Nullable<int> tid { get; set; }
        public Nullable<int> vtype { get; set; }
        public string completedate { get; set; }
        public Nullable<System.DateTime> addtime { get; set; }
        public Nullable<System.DateTime> visitime { get; set; }
        public Nullable<int> visituser { get; set; }
        public Nullable<int> attitude { get; set; }
        public Nullable<int> technology { get; set; }
        public Nullable<int> arrivalime { get; set; }
        public Nullable<int> servicetime { get; set; }
        public string remark { get; set; }
        public Nullable<int> zt { get; set; }
    }
}
